version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /resources
  static_dir: resources
- url: /stylesheets
  static_dir: stylesheets
- url: /.*
  script: event.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest